# syntax = docker/dockerfile:1.0-experimental

FROM sphinxdoc/sphinx-latexpdf:8.2.3

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl default-jre-headless && \
    curl -L "https://sourceforge.net/projects/plantuml/files/1.2023.7/plantuml.1.2023.7.jar/download" -o /usr/local/bin/plantuml.jar && \
    apt-get purge -y curl && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY doctools /hmd_transform/doctools
COPY requirements.txt .

RUN --mount=type=secret,id=pipconfig,dst=/etc/pip.conf \
    pip install --no-cache-dir -r requirements.txt

ENV TRANSFORM_INSTANCE_CONTEXT="{\"shell\": \"default\"}"

COPY ./meta-data /meta-data/
COPY ./python /src/python

RUN pip install --no-cache-dir -e /src/python/

ENV NID_CONTEXT=default

WORKDIR /app
COPY entrypoint.py .
COPY entry_puml.py .

CMD [ "python", "entrypoint.py" ]
